Namespace migration
Vonage/vonage-java-sdk pull request #300
Opened 2020-09-08 21:24 UTC by yallen011

*Updated Copyright
*Moved files to com.vonage.com

_Describe your changes here_

## Contribution Checklist
* [ ] Unit tests!
* [ ] Updated [CHANGELOG.md](CHANGELOG.md)
* [ ] My name is in [CONTRIBUTORS.md](CONTRIBUTORS.md)

2020-09-09 13:54 UTC, kellyjandrews requested changes
What I did do: reviewed all changes made
What I did not do: Run code, validate code not changed. 

Hope this helps.

2020-09-09 13:54 UTC, kellyjandrews commented on src/main/java/com/vonage/client/voice/SendDtmfMethod.java
> -import org.apache.http.client.utils.URIBuilder;
Verify this deletion was intentional

2020-09-09 13:54 UTC, kellyjandrews commented on src/test/java/com/vonage/client/auth/RequestSigningTest.java
> -import com.nexmo.client.auth.RequestSigning;
Does this need a replacement?

2020-09-09 13:54 UTC, kellyjandrews commented on src/test/java/com/vonage/client/voice/StopTalkMethodTest.java
> -import com.fasterxml.jackson.databind.ObjectMapper;
Just validating the deletions are intentional.

2020-09-09 13:54 UTC, kellyjandrews commented on src/test/java/com/vonage/client/application/ApplicationClientTest.java
>  import com.nexmo.client.application.capabilities.*;
Should this line also be removed?

2020-09-09 20:15 UTC, yallen011 commented on build.gradle
>                          email 'devrel@nexmo.com'
fixed

2020-09-09 20:31 UTC, yallen011 commented on LICENSE.txt
> +   Copyright [yyyy] [name of copyright owner]
fixed

2020-09-09 20:32 UTC, yallen011 commented on src/main/java/com/vonage/client/verify/VerifyEndpoint.java
> -    VerifyResponse verify(String number, String brand, String from, int length, Locale locale, VerifyRequest.LineType type) throws NexmoClientException {
this file is from com.nexmo I don't see it in the file when I look. I am not sure how you are seeing this deletion

2020-09-09 20:37 UTC, kellyjandrews commented on src/test/java/com/vonage/client/application/ApplicationClientTest.java
>  import com.nexmo.client.application.capabilities.*;
It appears as though this line is being replaced by `import com.vonage.client.application.capabilities.*;` on the new line 26. Is there a reason line 25 is being left in?

2020-09-09 20:37 UTC, kellyjandrews commented on README.md
> +containing the server sdk JAR, along with all the dependencies. Download the file, unzip it, and add the JAR files
SDK

2020-09-09 20:49 UTC, kellyjandrews approved these changes

2020-09-09 20:53 UTC, yallen011 commented on src/test/java/com/vonage/client/application/ApplicationClientTest.java
>  import com.nexmo.client.application.capabilities.*;
it was an unused import that didn't get removed by the IDE...good catch

2020-09-09 20:54 UTC, yallen011 commented on README.md
> +containing the server sdk JAR, along with all the dependencies. Download the file, unzip it, and add the JAR files
fixed

2020-09-09 20:54 UTC, yallen011 commented on src/test/java/com/vonage/client/voice/StopTalkMethodTest.java
> -import com.fasterxml.jackson.databind.ObjectMapper;
yes

2020-09-09 20:55 UTC, yallen011 commented on src/main/java/com/vonage/client/voice/SendDtmfMethod.java
> -import org.apache.http.client.utils.URIBuilder;
yes

2020-09-09 21:01 UTC, kellyjandrews requested changes

2020-09-09 21:01 UTC, kellyjandrews commented on README.md
> +containing the server sdk JAR, along with all the dependencies. Download the file, unzip it, and add the JAR files
server sdk -> Server SDK

2020-09-09 21:04 UTC, kellyjandrews requested changes

2020-09-09 21:04 UTC, kellyjandrews commented on build.gradle
> +    title "Vonage Java SDK"
Vonage Java Server SDK?

2020-09-09 21:05 UTC, yallen011 commented on README.md
> +containing the server sdk JAR, along with all the dependencies. Download the file, unzip it, and add the JAR files
fixed

2020-09-09 21:05 UTC, yallen011 commented on build.gradle
> +                name 'Vonage Java Client Library'
fixed

2020-09-09 21:07 UTC, yallen011 commented on build.gradle
> +    title "Vonage Java SDK"
fixed

2020-09-09 21:12 UTC, kellyjandrews approved these changes
I think you got everything now - lgtm

2020-09-09 21:43 UTC, slorello89 requested changes
Have not run anything yet, couple questions about namespaces that seem to be sticking around, and the copyright headers in the files.

2020-09-09 21:43 UTC, slorello89 commented on README.md
> +This library is released under the [Apache License][license]
Apache 2.0 I think would be more correct here?

2020-09-09 21:43 UTC, slorello89 commented on build.gradle
> +                        name 'Apache'
Does Gradle make a distinction between Apache and Apache 2.0?

2020-09-09 21:43 UTC, slorello89 commented on src/main/java/com/vonage/client/AbstractMethod.java
>   * Permission is hereby granted, free of charge, to any person obtaining a copy
Do all of the copyrights in the headers need to be updated as well? They are all MIT 😢  @dragonmantank?

2020-09-09 21:43 UTC, slorello89 commented on src/main/java/com/vonage/client/redact/RedactClient.java
>  import com.nexmo.client.*;
Should `com.nexmo.client` import still be here- does it still exist?

2020-09-09 21:43 UTC, slorello89 commented on src/main/java/com/vonage/client/verify/VerifyClient.java
>  import com.nexmo.client.*;
Another question about the com.nexmo.client namespace in this context.

2020-09-09 21:43 UTC, slorello89 commented on src/test/java/com/vonage/client/VonageClientTest.java
> +
extra whitespace

2020-09-09 21:43 UTC, slorello89 commented on src/test/java/com/vonage/client/application/ApplicationClientTest.java
> +
extra whitespace

2020-09-10 04:54 UTC, dragonmantank commented on src/main/java/com/vonage/client/AbstractMethod.java
>   * Permission is hereby granted, free of charge, to any person obtaining a copy
The headers can just be removed, not only because MIT isn't applicable anymore but (thankfully) Apache 2.0 only requires a LICENSE file in the root - https://www.apache.org/licenses/LICENSE-2.0#apply

You could put the shortform license at the top if Javadoc requires it, but otherwise since that text has to change anyway we might as well remove it and not worry about it.

The `(c)` also still needs removed from the Copyright section in the header block, it's not needed and redundant.

2020-09-10 11:53 UTC, bencgreenberg commented on README.md
>  [![Build Status](https://travis-ci.org/Nexmo/nexmo-java.svg?branch=version-2)](https://travis-ci.org/Nexmo/nexmo-java)
```suggestion
[![Build Status](https://travis-ci.org/Vonage/vonage-java-sdk.svg?branch=version-2)](https://travis-ci.org/Vonage/vonage-java-sdk)
```

2020-09-10 11:54 UTC, bencgreenberg commented on README.md
>  [![Maven Release](https://maven-badges.herokuapp.com/maven-central/com.nexmo/client/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.nexmo/client)
```suggestion
[![Maven Release](https://maven-badges.herokuapp.com/maven-central/com.vonage/client/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.vonage/client)
```

2020-09-10 11:54 UTC, bencgreenberg commented on README.md
> +You can use this Java Server SDK to add [Vonage's API](https://developer.nexmo.com/api) to your application. To use this, you'll
```suggestion
You can use this Java Server SDK to add [Vonage APIs](https://developer.nexmo.com/api) to your application. To use this, you'll
```

2020-09-10 11:56 UTC, bencgreenberg commented on README.md
> +* Check the [Javadoc](http://vonage.github.io/vonage-java-sdk/) for full reference documentation.
This redirects to https://github.com/Vonage/vonage-java-code-snippets, maybe just make it official here?

2020-09-10 11:57 UTC, bencgreenberg commented on README.md
>  * There are also **many useful code samples** in our [nexmo-community/nexmo-java-quickstart](https://github.com/nexmo-community/nexmo-java-quickstart) repository.
This redirects to https://github.com/Vonage/vonage-java-code-snippets so maybe just change it here?

2020-09-10 12:00 UTC, bencgreenberg commented on README.md
>  It is a good idea to [talk to us](https://nexmo-community-invite.herokuapp.com/)
Not sure why this is a custom heroku app link. It directs to https://developer.nexmo.com/community/slack

2020-09-10 13:01 UTC, slorello89 commented on src/main/java/com/vonage/client/verify/VerifyClient.java
It looks like the psd2 merge brought in some references to the old Nexmo exceptions which need to be pulled out.

2020-09-10 13:04 UTC, slorello89 commented on src/main/java/com/vonage/client/verify/VerifyEndpoint.java
> -    VerifyResponse verify(String number, String brand, String from, int length, Locale locale, VerifyRequest.LineType type) throws NexmoClientException {
If you pull down the branch this is definitely messed up - looks like it may have been a merge issue - causes a build error in `VerifyClient`

2020-09-11 14:28 UTC, yallen011 commented on build.gradle
> +                        name 'Apache'
idk honestly

2020-09-11 15:25 UTC, yallen011 commented on README.md
> +This library is released under the [Apache License][license]
fixed

2020-09-11 15:26 UTC, yallen011 commented on build.gradle
> +                        name 'Apache'
fixed

2020-09-11 15:26 UTC, yallen011 commented on src/main/java/com/vonage/client/AbstractMethod.java
>   * Permission is hereby granted, free of charge, to any person obtaining a copy
fixed. It looks like for java open source projects. The copyright is included in the top of each file.

2020-09-11 15:29 UTC, yallen011 commented on src/test/java/com/vonage/client/VonageClientTest.java
> +
IntelliJ actually does that automatically as a way to organize and group imports

2020-09-11 15:29 UTC, yallen011 commented on src/test/java/com/vonage/client/application/ApplicationClientTest.java
> +
IntelliJ actually does that automatically as a way to organize and group imports

2020-09-11 15:32 UTC, yallen011 commented on README.md
>  [![Build Status](https://travis-ci.org/Nexmo/nexmo-java.svg?branch=version-2)](https://travis-ci.org/Nexmo/nexmo-java)
I think we are getting rid of travis all together for Github Actions.

2020-09-11 15:33 UTC, yallen011 commented on README.md
>  [![Maven Release](https://maven-badges.herokuapp.com/maven-central/com.nexmo/client/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.nexmo/client)
I can just change this here and it will work?

2020-09-11 15:35 UTC, yallen011 commented on README.md
>  It is a good idea to [talk to us](https://nexmo-community-invite.herokuapp.com/)
i can change that to the redirected link instead.

2020-09-11 15:37 UTC, yallen011 commented on src/main/java/com/vonage/client/verify/VerifyClient.java
I didn't change these. In the PSD2 change. VonageResponseParseException gets thrown when the json can't be parsed and it returns the **Unable to parse response** error if I recall correctly

2020-09-11 19:42 UTC, slorello89 reviewed
Few references to com.nexmo.client lingering.

2020-09-14 07:07 UTC, bencgreenberg commented on README.md
>  [![Maven Release](https://maven-badges.herokuapp.com/maven-central/com.nexmo/client/badge.svg)](https://maven-badges.herokuapp.com/maven-central/com.nexmo/client)
Yeah, that's why I prefer to offer suggestions like this when I can rather than a comment. If you commit the suggestions inside the GitHub UI then it'll add it to the code in this PR for you.

2020-09-14 11:20 UTC, alphacentauri82 commented
LGTM

2020-09-15 15:28 UTC, slorello89 approved these changes
LGTM

2020-09-15 15:29 UTC, merged