Made CI changes
Vonage/vonage-java-sdk pull request #302
Opened 2020-09-15 21:17 UTC by yallen011

- Added github actions
- Updated badges
- Removed Travis CI

2020-09-15 21:24 UTC, slorello89 commented
I don't see a GitHub action kicking off?

2020-09-15 21:30 UTC, yallen011 commented
could that be because it is not in master yet?

2020-09-16 13:48 UTC, dragonmantank requested changes

2020-09-16 13:48 UTC, dragonmantank commented on .github/workflows/build.yml
> +      - name: Run Codecov
While Travis CI didn't seem to do it either, can we add a step to run the unit tests and make sure that the library compiles?

2020-09-16 13:48 UTC, dragonmantank commented on README.md
> +[![Build Status](https://github.com/vonage/vonage-java-sdk/workflows/build/badge.svg)](https://github.com/Vonage/vonage-java-sdk/actions?query=workflow%3Abuild)
The path for the badge and link need to use the `name` value used in the YAML file, not the filename itself.

2020-09-16 13:48 UTC, dragonmantank commented on .github/workflows/build.yml
> +name: Java Core
Can we have this more in-line with what this file is doing? Calling it "Build" or "CI" or something more descriptive than "Java Core" would be useful as we add more workflows down the road

2020-09-16 13:48 UTC, dragonmantank commented on .github/workflows/build.yml
> +    runs-on: ubuntu-latest
Can we expand this to Windows and MacOS?

2020-09-16 13:48 UTC, dragonmantank commented on codecov.yml
>    bot: judy2k
Can we change this value or remove it?

2020-09-16 14:37 UTC, yallen011 commented on README.md
> +[![Build Status](https://github.com/vonage/vonage-java-sdk/workflows/build/badge.svg)](https://github.com/Vonage/vonage-java-sdk/actions?query=workflow%3Abuild)
fixed

2020-09-18 15:34 UTC, yallen011 commented on .github/workflows/build.yml
> +name: Java Core
fixed

2020-09-18 15:34 UTC, yallen011 commented on .github/workflows/build.yml
> +    runs-on: ubuntu-latest
added

2020-09-18 15:36 UTC, yallen011 commented on codecov.yml
>    bot: judy2k
Just for clarity, why do you want it to be removed?

2020-09-18 15:38 UTC, dragonmantank commented on codecov.yml
>    bot: judy2k
He no longer works here, so we don't need his naming showing up in automated messages or notifications.

2020-09-18 18:59 UTC, yallen011 commented on codecov.yml
>    bot: judy2k
I don't know how to create a different bot. Removing that bot will cause a different bot to be used and I don't know what that bot will do or what will be different. I think it will use the team bot tho, which I don't think is set.

2020-09-21 14:53 UTC, slorello89 commented
@yallen011 - It looks like the windows machine is not replacing the `-----BEGIN PRIVATE KEY-----` correctly from the keys and a `-` is bleeding into the private key it's trying to parse (hence the 2d illegal character - which it's reading as `2d`).

My guess is that this is an issue in the [JWT library](https://github.com/Nexmo/nexmo-jwt-jdk/blob/master/src/main/kotlin/com/nexmo/jwt/KeyConverter.kt#L44) - which is assuming the line ending type of the first line.

see: https://www.prostdev.com/post/understanding-the-illegal-base64-character-error-java-groovy-and-mule-4-dw-2-0

2020-09-25 16:13 UTC, dragonmantank approved these changes

2020-09-25 16:14 UTC, merged