Fix: Error from no-content responses
Vonage/vonage-java-sdk pull request #304
Opened 2020-09-28 19:02 UTC by vyj7

_Problem: Logging an empty response was throwing IllegalArgumentException from EntityUtils
  Solution: For an empty response log nothing by adding a Null check_

## Contribution Checklist
* [ ] Unit tests!
* [ ] Updated [CHANGELOG.md](CHANGELOG.md)
* [ ] My name is in [CONTRIBUTORS.md](CONTRIBUTORS.md)

2020-10-05 13:43 UTC, slorello89 commented
Hi @vyj7 - this looks like it ought to fix the issue, however without a Unit Test there's no way to set up a regression to validate that it won't happen again in the future - can you please add a unit test to this PR to make sure it doesn't toss the exception anymore? Thanks

2020-10-05 13:43 UTC, slorello89 requested changes
Missing Unit Tests

2020-10-05 16:55 UTC, vyj7 commented
@slorello89  I have added UT for LoggingUtils Class

2020-10-05 18:07 UTC, slorello89 approved these changes
Outstanding, thank you for this PR - very helpful! Happy Hacktoberfest!

2020-10-05 18:08 UTC, slorello89 commented
@yallen011  - I'll leave this for you to merge but it looks all good in my book!

2020-10-21 00:49 UTC, yallen011 approved these changes
looks good to me. Thank you for contributing to the Vonage Java Server SDK and Hacktoberfest 👻 🎃

2020-10-21 00:49 UTC, merged