Update BasicInsightRequest.java
Vonage/vonage-java-sdk pull request #312
Opened 2020-10-01 05:15 UTC by poornapragna877

Removed unnecessary references to "this" keyword

_Describe your changes here_

## Contribution Checklist
* [ ] Unit tests!
* [ ] Updated [CHANGELOG.md](CHANGELOG.md)
* [ ] My name is in [CONTRIBUTORS.md](CONTRIBUTORS.md)

2020-10-08 19:52 UTC, yallen011 requested changes

2020-10-08 19:52 UTC, yallen011 commented on src/main/java/com/vonage/client/insight/BasicInsightRequest.java
> -            this.number = number;
The `this` keyword was only supposed to be removed from places that didn't need it. You removed the keyword from places that did need it as well as from places that did need it which are causing the test to fail. Can you fix the changes that are causing the tests to fail. Then run a `./gradlew build`(on a mac) or `gradlew.bat build`(on a Windows machine) on your local machine to make sure the build pass then push up the changes. If you need help understanding the changes that need to be made please let me know.

2020-10-08 20:43 UTC, yallen011 commented
please add the changes from your closed PR #313 to this one. Thank you

2020-10-13 10:12 UTC, lukeocodes commented
@poornapragna877 please address the requested changes so we can merge or close this PR. Thanks for your contribution!

2020-11-06 06:04 UTC, yallen011 commented
This PR has gone stale. No response from requestor. Closing

2020-11-06 06:04 UTC, closed without merging