Remove unnecessary references to the "this" keyword
Vonage/vonage-java-sdk pull request #334
Opened 2020-10-02 04:16 UTC by ILGO0413

Redundant "this" references are removed.

2020-10-15 11:30 UTC, imabhinavagarwal approved these changes

2020-10-15 11:30 UTC, imabhinavagarwal requested changes
resolve conflicts

2020-10-20 23:21 UTC, yallen011 requested changes
Hi @ILGO0413 can you please rebase with master. You can see how to do this properly here. https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a and fix any merge conflict before doing the force push.

2020-10-29 19:50 UTC, yallen011 approved these changes
Thanks for fixing conflicts. Looks good. Happy Hacktoberfest 👻 🎃

2020-10-29 19:50 UTC, merged