Create SHA256 Hashing option
Vonage/vonage-java-sdk pull request #341
Opened 2020-10-06 14:39 UTC by sirNikolai

Addresses issue #229 
Make a more one way approach to retrieving hashes and add another builtin java security hashing algorithm SHA-256

## Contribution Checklist
* [ ] Unit tests!
* [ ] Updated [CHANGELOG.md](CHANGELOG.md)
* [ ] My name is in [CONTRIBUTORS.md](CONTRIBUTORS.md)

2020-10-06 15:10 UTC, sirNikolai commented on src/main/java/com/vonage/client/auth/hashutils/MD5Util.java
> +class MD5Util extends Hasher {
My only qualm with this is hoping that it did not break any API agreements that the SDK has. Otherwise all other methods are refactored to work as intended with this as an added feature without breaking any contracts.

2020-10-07 06:35 UTC, JamiesWhiteShirt commented
I can't seem to figure out how you would configure a `VonageClient` to use a different signature with these changes. The changes seem to be mostly internal. Should perhaps a `HashUtil.HashType` be configurable in the `VonageClient.Builder`?

2020-10-07 11:57 UTC, sirNikolai commented
I see what you mean. I'll change it up in the regard.

2020-10-07 12:47 UTC, sirNikolai commented on src/main/java/com/vonage/client/VonageClient.java
> +        private HashUtil.HashType hashType = HashUtil.HashType.MD5;
main reason for the default is to prevent existing API breakages.

2020-10-07 12:48 UTC, sirNikolai commented on src/main/java/com/vonage/client/auth/SignatureAuthMethod.java
> +    public SignatureAuthMethod(String apiKey, String secret, HashUtil.HashType hashType) {
potentially needs an overload but will leave to your judgement. Otherwise this could maybe be a breaking change.

2020-10-07 16:17 UTC, sirNikolai commented
This will require another refactor though to get HMAC SHA256 added in for example since right now the secret key is just appended to the end of the string when for HMAC it should be passed in separately. Can probably do it as part of this PR but again not sure what the bounds of this is.

2020-10-26 19:51 UTC, slorello89 requested changes

2020-10-26 19:51 UTC, slorello89 commented on src/main/java/com/vonage/client/auth/hashutils/HashUtil.java
> +        SHA256,
We don't support a straight SHA256 hash - we only support the [HMAC](https://developer.nexmo.com/concepts/guides/signing-messages).

2020-10-26 19:51 UTC, slorello89 commented on src/main/java/com/vonage/client/auth/hashutils/HashUtil.java
> +        HMAC_SHA256
be really cool if we could get `HMAC_SHA512` as well (we also support SHA1 but I think it's fine not to include it)

2020-10-26 19:51 UTC, slorello89 commented on src/main/java/com/vonage/client/auth/hashutils/MD5Hasher.java
> -    public static String calculateMd5(String input, String encoding) throws NoSuchAlgorithmException, UnsupportedEncodingException {
`calculateMd5` should be left in - even if it's just being routed through calculate - removing it is a breaking change.

2020-10-26 19:53 UTC, sirNikolai commented on src/main/java/com/vonage/client/auth/RequestSigning.java
> +     protected static void constructSignatureForRequestParameters(List<NameValuePair> params,
Refer to previous comment

2020-10-26 19:54 UTC, sirNikolai commented on src/main/java/com/vonage/client/auth/hashutils/HashUtil.java
> +    public static HashUtil getInstance() {
yeah, this can be a static helper class. In retrospect not sure why I decided on singleton

2020-10-26 19:55 UTC, slorello89 commented on src/main/java/com/vonage/client/auth/hashutils/HashUtil.java
> +    public static HashUtil getInstance() {
👍

2020-10-26 19:56 UTC, sirNikolai commented on src/main/java/com/vonage/client/auth/RequestSigning.java
> +        return verifyRequestSignature(request, secretKey, System.currentTimeMillis(), hashType);
Refer to first comment on optionals

2020-10-26 19:57 UTC, slorello89 commented on src/main/java/com/vonage/client/auth/RequestSigning.java
> +    public static void constructSignatureForRequestParameters(List<NameValuePair> params, String secretKey, HashUtil.HashType hashType) {
TIL - cool (mostly a .NET dev so don't think I've ever noticed that about Java). Couple places where you've changed the signature rather than adding an override - in those spots definitely add an override so we don't induce a breaking change.

2020-10-26 19:57 UTC, sirNikolai commented on src/main/java/com/vonage/client/auth/hashutils/HashUtil.java
> +        SHA256,
Made that first before realising. I can either take it out entirely or keep it in and just remove the enum, making it unusable externally

2020-10-26 19:57 UTC, sirNikolai commented on src/main/java/com/vonage/client/auth/hashutils/HashUtil.java
> +        HMAC_SHA256
yeah can add that in lieu of just SHA 256

2020-10-26 19:58 UTC, sirNikolai commented on src/main/java/com/vonage/client/auth/RequestSigning.java
> +    public static void constructSignatureForRequestParameters(List<NameValuePair> params, String secretKey, HashUtil.HashType hashType) {
documented that in the initial comment, was wondering if I should support that as legacy. I'll just re-add them back in and deprecate calculateMd5.

Also I do miss optionals and default values from .NET

2020-10-26 20:00 UTC, slorello89 commented on src/main/java/com/vonage/client/auth/hashutils/HashUtil.java
> +        HMAC_SHA256
that would be awesome

2020-10-26 20:03 UTC, slorello89 commented on src/main/java/com/vonage/client/auth/RequestSigning.java
> +    public static void constructSignatureForRequestParameters(List<NameValuePair> params, String secretKey, HashUtil.HashType hashType) {
Yeah so these libraries are strict adherents to [semver](https://semver.org/) so breaking public methods is only really allowable between major versions. If your changes are making a method become obsolete feel free to tag it as such so people know which method to use but everything should be backward compatible so peoples code doesn't break 😃

2020-10-27 14:02 UTC, slorello89 requested changes
Hi @sirNikolai - Just a couple more notes - I think I gave you the wrong impression - we don't support a SHA-1 hash - we only supported it as an HMAC so I'm sorry 😭. I'm Going to try running these locally to confirm they work will let you know if I find anything else while I'm doing that. thanks!

2020-10-27 14:02 UTC, slorello89 commented on src/main/java/com/vonage/client/auth/hashutils/AbstractHasher.java
> +        } catch (UnsupportedEncodingException | InvalidKeyException e) {
Another spot where the exceptions should be advertised and thrown.

2020-10-27 14:04 UTC, sirNikolai commented
@slorello89 cool cool. I'll wait for the local testing and then do the remaining changes once everything is done there.

2020-10-27 17:31 UTC, slorello89 commented on src/main/java/com/vonage/client/auth/RequestSigning.java
> +            if (!MessageDigest.isEqual(hashed.getBytes("UTF-8"), suppliedSignature.getBytes("UTF-8")))
There's a bit of an issue here, for the HMACs they come in as uppercase, however, the hashed value generated is lower case - they're just integers so it ought to be case agnostic. This could be fixed as easily as sending both the hashed and supplied signature value to lowerCase before checking their equality. Unless you want to do something fancy 😄

2020-10-27 17:42 UTC, slorello89 commented
@sirNikolai - I had one more comment after my testing, the verifyRequest doesn't work for HMACs as they come in from Vonage in upper case, and the calculate method produces the HMAC in lower case, they ought to be case agnostic but this always worked with the md5 hash because it just so happens to come in as a lower-case 🙃. If you want to add the two extra methods (HMAC SHA-1- and I forgot we also have HMAC-MD5) that would be much appreciated, otherwise I think what you've provided is easy enough to adapt to the other methods

2020-10-28 01:09 UTC, sirNikolai commented
@slorello89 wish I had the capacity to do something less cheaty to lowercase, buuuuuuut if it'll work then so be it

2020-10-28 14:25 UTC, slorello89 approved these changes
@sirNikolai - thank you so much for this - ran through send / receive on each of the different signing types and everything works perfectly - everything looks great from my perspective so I'm approving it. @yallen011 - I leave it to you to actually merge this - but this PR looks awesome.

thanks again Nik - Happy Hacktoberfest 👻 🎃 💀 !

2020-10-28 14:27 UTC, sirNikolai commented
Thanks! Hopefully this is trivial enough to extend if you enable more hashing types in the future.

2020-10-29 14:22 UTC, merged