Add ASR
Vonage/vonage-java-sdk pull request #353
Opened 2020-10-28 11:12 UTC by yallen011

_Describe your changes here_

## Contribution Checklist
* [x] Unit tests!
* [x] Updated [CHANGELOG.md](CHANGELOG.md)
* [x] My name is in [CONTRIBUTORS.md](CONTRIBUTORS.md)

2020-10-29 19:51 UTC, slorello89 requested changes

2020-10-29 19:51 UTC, slorello89 commented on src/main/java/com/vonage/client/incoming/InputEvent.java
> -    private String dtmf;
This is going to be a breaking change for some people it doesn't break the DTMF code snippet since they don't have to worry about the type in the string format. But anyone who's doing something like:

```java
String digits = inputtResult.getDtmf();
```

Is going to break. Unless they specify what the generic type is when they are creating the event, which they wouldn't have had to do before. 

You can keep the dtmf field as generic, but I think it might be wiser to have the getter be a string, and perhaps have other fields for timed out.

What are your thoughts @dragonmantank?

2020-10-29 20:30 UTC, yallen011 commented on src/main/java/com/vonage/client/incoming/InputEvent.java
> -    private String dtmf;
ok, there was an assumption that if you are doing ASR you are going to use the generic but if you are doing DTMF the old way you wouldn't have to use the generic because dtmf would come back as a string which wouldn't through an error when you called `getDTMF()`. But if you are going to adapt the new way of send DTMF then you would use the generic. That was the assumption. I could add more verbiage to the javadoc to help with that but these are the assumptions made and this is the best trade-off I could find. This is not going to remain permanent since the plan is to remove the deprecated fields and the generic to just use DtmfResult as the datatype for dtmf in the next major release.

2020-10-29 21:01 UTC, slorello89 commented on src/main/java/com/vonage/client/incoming/InputEvent.java
> -    private String dtmf;
Aye, I see that - however since the return type of `getDtmf` is generic, if you don't explicitly tell the compiler what the type is, it can't infer it as a string (hence why this would be a breaking change). I'm not sure if you can do this in java, but you can may be able to keep the original class non-generic and have a new `InputEvent` class that is generic and mark the old class as deprecated altogether?

2020-11-03 19:38 UTC, yallen011 commented on src/main/java/com/vonage/client/incoming/InputEvent.java
> -    private String dtmf;
It will still work without specifying the generic type when using getDTMF() for DTMF only the old way. The problem will arise from doing DTMF and/or Speech the new way. I can't do 2 InputEvent files but I can do InputEventv2 but since my concern is about the fact that this is deprecated and will go away eventually anyway so creating a InputEventv2 file only to later remove it and put everything in InputEvent later seems cumbersome. @dragonmantank given the situation, can we go ahead with this being a breaking change? I don't think we can avoid having a breaking change here. No matter what route we choose. All roads lead to a breaking change...whether it be now or later. Once we deprecate, it will be another breaking change so we can do a breaking change to allow support for both for a time then break it again when we remove or we can just make it so we only support new DTMF and only have 1 breaking change for this feature.

2020-11-04 16:14 UTC, dragonmantank commented on src/main/java/com/vonage/client/incoming/InputEvent.java
> -    private String dtmf;
### tl;dr - If we can't do this without it being a breaking change, remove the old way and cut a major release.

Ultimately any solution we provide we want to give customers the chance to upgrade as soon as possible. We deprecated old functionality and load the new functionality along-side. Existing customers can continue to use the old syntax until they get a chance to migrate. When a user can use new functionality without upgrading major versions, it's a huge win. It's more work on our side to do that, but ultimately we're here to make the developer's lives easier. Upgrading to a new major version isn't always something a developer can just do.

The decision is up to you. If we simply cannot provide a solution that enables the old syntax as well as the new syntax, we'll have to ship it as a breaking change and a new major version. If we're doing the breaking change, just rip out the old DTMF-only Input and replace it with the new DTMF+ASR syntax. 

> All roads lead to a breaking change

You're correct. The question _we_ have to ask ourselves is where do we make that fork in the road. Do we add additional lanes and signage to help developers know that the fork is coming up and give them a chance to change lanes, or do we just plop down an off-ramp. 

> Once we deprecate, it will be another breaking change

Not quite. Deprecating a feature is not removing functionality, so that's a minor change. We're alerting the user that this code path is going away. By providing the new way alongside the deprecated way, we give the user a chance to upgrade. _That might not always be possible_, but that doesn't mean we shouldn't try. 

Deprecated features can, and should, be removed at the next major release. We are then free to remove deprecated features at any major version release, at our discretion. So something deprecated in 5.x can be removed in 6.0.0. Anything deprecated in 6.x can be removed in 7.0.0. That major release can come six months later, or six days later, it doesn't matter. We get the ability to remove functionality only at a major release, so that's when we flush out deprecated features.

2020-11-10 16:00 UTC, yallen011 commented on src/main/java/com/vonage/client/incoming/InputEvent.java
> -    private String dtmf;
After talking further with @dragonmantank I have decided to gut out the old DTMF stuff and make it breaking change. This will result in a v6 release. I will submit another PR that will have all the old DTMF stuff removed.

2020-11-11 23:59 UTC, yallen011 commented
@dragonmantank @slorello89 updated sdk and code snippets to include the dtmf portion of the asr changes.

2020-11-12 18:05 UTC, slorello89 approved these changes
Only comments are flagging the things that I expect to be removed before 6.0.0 is released. Otherwise, I've tested the snippets and they look good.

2020-11-12 18:05 UTC, slorello89 commented on CHANGELOG.md
> +## [6.0.0]
Just for clarity - are we going to have a 5.7.0 that has both the new Input stuff and the outmoded DTMF stuff, and then a 6.0.0 that removes it all?

2020-11-12 18:05 UTC, slorello89 commented on src/main/java/com/vonage/client/incoming/InputEvent.java
> +     *Deprecated. Use {@link DtmfResult#isTimedOut()}
Just want to make sure this doesn't work it's way in to 6.0.0.

2020-11-12 18:05 UTC, slorello89 commented on src/main/java/com/vonage/client/voice/ncco/InputAction.java
> +     * @param builder  builder to create InputAction object
Just want to make sure this doesn't work it's way in to 6.0.0.

2020-11-12 21:40 UTC, yallen011 commented on src/main/java/com/vonage/client/incoming/InputEvent.java
> +     *Deprecated. Use {@link DtmfResult#isTimedOut()}
good catch. Removed

2020-11-12 21:42 UTC, yallen011 commented on src/main/java/com/vonage/client/voice/ncco/InputAction.java
> +     * @param builder  builder to create InputAction object
Not sure what is wrong with this one? Because this is for 6.0.0 release, we are making the InputAction constructor private and the builder will now be used exclusively instead of allowing for the constructor to be used directly.

2020-11-16 06:42 UTC, merged