Update Insight to be consistent with current API
Vonage/vonage-java-sdk pull request #389
Opened 2022-06-28 13:10 UTC by SMadani

Currently, `com.vonage.client.insight` doesn't support the "real_time_data" field, which was added to the Numbers Insight API, along with some missing "status" responses in Advanced insights. This PR not only addresses these omissions, but also improves the quality of support for the API by adding further validation and tests, achieving 100% code coverage as well.

2022-07-13 15:40 UTC, dragonmantank requested changes
Couple of changes/questions

2022-07-13 15:40 UTC, dragonmantank commented on src/main/java/com/vonage/client/insight/Reachability.java
> + *   Copyright 2020 Vonage
Noticed on a few other new files, this should be 2022

2022-07-13 15:40 UTC, dragonmantank commented on src/main/java/com/vonage/client/insight/StandardInsightResponse.java
> +    public String getCallerName() {
This might be something to be brought up to the VAPI team, but why are we exposing this information twice? Seems odd that we have both a `CallerIdentity` and this in the responses (I know the SDK is just reflecting the actual response, but should these direct exposures be deprecated in the API?) Might be useful to get that answered before we add new code that might turn around and be deprecated.

2022-07-13 15:48 UTC, SMadani commented on src/main/java/com/vonage/client/insight/Reachability.java
> + *   Copyright 2020 Vonage
Everything in the repo except Messages API is 2020 so I'll open a separate PR to update these

2022-07-13 15:49 UTC, dragonmantank commented on src/main/java/com/vonage/client/insight/Reachability.java
> + *   Copyright 2020 Vonage
+1

2022-07-13 15:49 UTC, SMadani commented on src/main/java/com/vonage/client/insight/StandardInsightResponse.java
> +    public String getCallerName() {
I agree, this puzzled me too. Same with the [`handset_status`](https://vonage.slack.com/archives/CD2JDM09M/p1656670938668069), which has undocumented values yet could very well be be a Boolean.

2022-07-13 15:50 UTC, dragonmantank commented on src/main/java/com/vonage/client/insight/AdvancedInsightRequest.java
> +    @Deprecated
If we can't do a final 6.x release then no big deal, we can leave the deprecation here. Just would be nice to excise it now properly, but still alert the users.

2022-07-13 16:00 UTC, SMadani commented on src/main/java/com/vonage/client/insight/AdvancedInsightRequest.java
> +    @Deprecated
Well, we didn't deprecate the Search API in the SDK and now it's completely gone. In an ideal world deprecations would happen before removals I agree. Though perhaps in this case it is better to leave it as deprecated since the API itself marks it as deprecated, not removed.

2022-07-20 00:12 UTC, dragonmantank approved these changes
LGTM

2022-07-20 10:36 UTC, merged