feat: Add Number Insight v2
Vonage/vonage-java-sdk pull request #507
Opened 2024-01-10 18:16 UTC by SMadani

Implements [NI v2 spec](https://developer.vonage.com/en/api/number-insight.v2].

2024-01-10 19:13 UTC, maxkahan approved these changes

2024-01-10 19:15 UTC, maxkahan requested changes

2024-01-10 19:15 UTC, maxkahan commented on src/main/java/com/vonage/client/numberinsight2/FraudCheckRequest.java
> +	 * Accepted value is “phone” when a phone number is provided.
The quotes on this line are causing an error on Windows

2024-01-11 10:26 UTC, SMadani commented on src/main/java/com/vonage/client/numberinsight2/FraudCheckRequest.java
> +	 * Accepted value is “phone” when a phone number is provided.
Good catch! Thanks

2024-01-11 14:27 UTC, maxkahan approved these changes

2024-01-11 14:28 UTC, merged